### ISSUE TITLE
BUG: Email Preview Exposed HTML Tags - Personalisations within Hyperlinks

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-utils#127] opened 2023-06-21 12:54 UTC
## Overview of Current Behavior
When you preview an email within portal and the content of template includes a hyperlink where the url is partially comprised of a personalisation, then you will see extra characters, closing parentheses ")", and/or `</mark>` `</span>` html tags exposed.

## Steps to Reproduce
_This can occur in any portal environment, but for these steps to reproduce we will use staging_

### In Portal:
1. Log into https://staging.notifications.va.gov as either a platform admin or editor within a service
2. Choose your desired service (Product Sandbox for example)
3. Create a new email template or edit an existing email template
4. Add a hyperlink to the email content that includes a personalisation partially within the url. See full list of use cases below in image A.
5. Click the preview tab in the email editor
6. See result in image B
7. Please note: this preview also appears after you've saved the email content (not just in edit mode)

Markdown Version (A)
> Items 1 - 3 illustrate the issue
> Items 4 - 6 are control comparisons for what normal hyperlinks and personalisations look like
![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/989a7143-afba-4dd2-9599-f431f297eb94)

Preview Version (B)
![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/976d30f5-ea16-4103-b30c-cf0b0c814dcd)

### In Postman:

1. Choose Staging Env
2. Add the applicable variables into your environment for notification-api-url, service-id, service-api-key, and template-id
3. Navigate to service > template> **get html preview**
4. Click send on the get
5. Narrow in on the html content that contains the hyperlink:
`<a style=\"word-wrap: break-word; color: #004795;\" href=\"https://va.gov/<span class='placeholder'><mark>((url\" target=\"_blank\">hyperlink text here</a>)&lt;/mark&gt;&lt;/span&gt;)`

## Additional Info
- Notification Utils location: `notifications_utils/field.py`, the `Field` class.
- This appears to be regex-related - We may need a new regex specifically for this
- The portal uses the following notification-api endpoints for previewing emails:
    - `/service/<uuid:service_id>/template/<template_id>/preview-html`
    - `/service/<uuid:service_id>/template/generate-preview`
- Currently the preview adds span and mark tags to show a highlighted personalisation in the email preview so users understand this is dynamic content that will be replaced by real values they provide. 
- The issue does NOT occur when the personalization represents the entire URL within the hyperlink
- See highlighted ((ok)) personalisation below:

![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/7a396642-f72e-4d52-b58e-08a634d69146)

## Impact
When a client adds a personalisation to their email template within a url, then their preview makes it look like there is an html issue within the template. This could be confusing.

The actual email send is unaffected and formatted correctly when the client passes through the applicable value for the personalisation.

## Expected Behavior

- [x] When a hyperlink contains a placeholder(aka personalisation) it should be treated as plain text within a URL and remain hidden behind the hyperlink
- [x] The placeholder highlighting style (span and mark tags) is not used within hyperlinks when transformed into preview HTML

## Acceptance Criteria
SCENARIO - You are logged into the Self Service UI as a platform admin or editor within a service and are editing an email template
___
GIVEN you add a hyperlink where the entire URL is a personalisation
WHEN you click on the preview tab
THEN only you see the provided hyperlink text in the normal style

GIVEN you add a hyperlink where the beginning of the URL is a personalisation and the trailing content is static text
WHEN you click on the preview tab
THEN only you see the provided hyperlink text in the normal style

GIVEN you add a hyperlink where the middle of the URL is a personalisation and the surrounding content is static text
WHEN you click on the preview tab
THEN only you see the provided hyperlink text in the normal style

GIVEN you add a hyperlink where the beginning of the URL is static text and the end is a personalisation
WHEN you click on the preview tab
THEN only you see the provided hyperlink text in the normal style
____
GIVEN you add a hyperlink where the entire URL is a personalisation
WHEN you click on the preview tab and hover over the hyperlink
THEN you see a preview of the URL which only contains the personalisation placeholder text wrapped in double parentheses

GIVEN you add a hyperlink where the beginning of the URL is a personalisation and the trailing content is static text
WHEN you click on the preview tab and hover over the hyperlink
THEN you see a preview of the URL which contains the static text you entered followed by the personalisation placeholder text wrapped in double parentheses

GIVEN you add a hyperlink where the middle of the URL is a personalisation and the surrounding content is static text
WHEN you click on the preview tab and hover over the hyperlink
THEN you see a preview of the URL which contains the prefix static text you entered, the personalisation placeholder text wrapped in double parentheses, and the trailing static text you entered

GIVEN you add a hyperlink where the beginning of the URL is static text and the end is a personalisation
WHEN you click on the preview tab and hover over the hyperlink
THEN you see a preview of the URL which contains the prefix static text you entered, the personalisation placeholder text wrapped in double parentheses, and the trailing static text you entered

## QA Considerations
**This should be QAed by both Strike and Notify teams - please keep Strike looped in so they can plan accordingly**

- Strike should validate the Portal behaves as expected on any preview pages when personalisations and hyperlinks are used

- Notify should validate the applicable API routes and email send functionality still behave as expected, including the style of the received email
    - `/service/<uuid:service_id>/template/<template_id>/preview-html`
    - `/service/<uuid:service_id>/template/generate-preview`
    - `/v2/notifications/email`

**Comment by mjones-oddball** [comment] 2023-06-26 14:47
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-utils/127?planning-poker) with Zenhub @cris-oddball @EvanParish @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by tabinda-syed** [comment] 2023-07-05 17:21
At the Llama Refinement today, it was discussed that Strike will need to QA this as well once it is done.

**Comment by mjones-oddball** [comment] 2023-07-11 14:10
Here is the markdown copy of my template from the description in case you need to recreate it!
`1. Hyperlink where url is comprised of part static text and part personalisation at the end 
[partial url end](https://www.partial.com/((url)))
2. Hyperlink where url is comprised of part static text and part personalisation in the middle
[partial url middle](https://www.partial.com/((url))%whatever)
3. Hyperlink where url is comprised of part static text and part personalisation in the beginning
[partial url beginning](((url))/whateveryouwanthere)
4. Hyperlink where personalisation represents the entire url 
[full url](((url)))
5. Plain Personalisation: ((ok))
6. Plain Hyperlink without Personalisation: [plain jane static url](https://www.google.com)`

**Comment by npmartin-oddball** [comment] 2024-08-15 15:40
Need to test/determine if this is still valid. @cris-oddball will test.

**Comment by EvanParish** [comment] 2024-08-20 21:55
Started looking into this issue. I was able to reproduce it in my testing and identify where it is happening.

**Comment by EvanParish** [comment] 2024-08-23 14:25
I made some great progress yesterday and I'm pushing my code to dev for testing. As long as testing goes well I'll have my PR up once my testing is complete.

**Comment by EvanParish** [comment] 2024-08-23 16:38
In testing the fix there are a couple places that things were either not fixed, or now do not receive formatting, see below.

Raw email text while editing:
<img width="757" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkdEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e4d37a5345bf33aa7657dcaa45da79569737076/image.png" alt="image.png" />

Email preview:
<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlNEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65cee3d777ce12f6657e997f6c29a6bd283b6664/image.png" alt="image.png" />

As you can see from edge cases there are still a couple problems.
1. The formatting of placeholders (personalisation) will not be applied in a markdown link text if there is also a placeholder within the link itself.
2. The formatting still gets messed up, like it does now, in some cases if the placeholder is a part of a second or later query parameter. It must be if the link has certain characters in it that cause the formatting to get a little messy before the fix is applied.

I'm unsure of the amount of effort it will take to fix these cases. I have only looked into them briefly, and I'm unsure about the amount of effort we want to put towards fixing all edge cases in general. It seems the first one is more likely to happen than the second and could end up being confusing to some users. The formatting is messed up in the same manner as before the bugfix with the second case.

**Comment by EvanParish** [comment] 2024-08-26 19:10
I reworked this so there are not more broken edge cases and the AC is now met. Previously I was simply removing the formatting around placeholders, but that doesn't meet the AC, so it has been reworked to temporarily replace the placeholder parentheses within markdown links, then put them back after the text is converted to HTML. As you can see in the image below, everything seems to be working, except the formatting is messed up when using the "Send test email" button in the portal. The template ID for this is: `d4203294-3cd7-41c6-a8bc-f76d3c2274cf' in the VA Notify service.

<img width="848" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMktKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce66c9e9fad77f23d5bb34a8856e0a17c9689872/image.png" alt="image.png" />

**Comment by EvanParish** [comment] 2024-08-26 21:00
Sending test emails is no longer broken! This is now how it will show up when a test email is sent. Hovering over the links shows the placeholders with parentheses as expected.

![image](https://github.com/user-attachments/assets/dd1d8c89-4a94-4ee1-acc4-ba654f0bbc39)

**Comment by cris-oddball** [comment] 2024-08-27 14:39
PR Approved and Merged, sending to Perf for manual validation.

**Comment by cris-oddball** [comment] 2024-08-27 16:02
**QA PASSED**

I promoted the template Evan set up in Dev to Perf. Template ID is `c7e39628-28e8-4601-9e36-c63b374381cf`.

When previewing the template in Portal, the template looks as expected. This template has all of scenarios listed in the description.

- Portal Edit mode:
<img width="836" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFdQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ec552af44225576a8660b195e7015f3f098f2f6/Screenshot%202024-08-27%20at%209.17.52%E2%80%AFAM.jpg" alt="Screenshot 2024-08-27 at 9.17.52 AM.jpg" />

- Portal Preview mode:
<img width="1305" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGFQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85a89255fe2a7821de43778525cd8ab02a55c121/Screenshot%202024-08-27%20at%209.27.27%E2%80%AFAM.jpg" alt="Screenshot 2024-08-27 at 9.27.27 AM.jpg" />


- Route GET  `/service/<uuid:service_id>/template/<template_id>/preview-html` returns the expected HTML preview:
<img width="664" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHFQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbcd70bacd7fafc89845097dd3133fd0315606f9/Screenshot%202024-08-27%20at%209.26.57%E2%80%AFAM.jpg" alt="Screenshot 2024-08-27 at 9.26.57 AM.jpg" />

- ROUTE POST `/service/<uuid:service_id>/template/generate-preview` with the content passed in the post payload returns the expected preview:
<img width="1083" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f9c07b0905bb133f127594c0b4a134b1e065842/Screenshot%202024-08-27%20at%209.53.07%E2%80%AFAM.jpg" alt="Screenshot 2024-08-27 at 9.53.07 AM.jpg" />


- Sending a notification with that template and the personalisation delivers an email that looks as expected: 
<img width="1401" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDZQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53265ed8a4b015796e40f4e1a58ad447b81671c4/Screenshot%202024-08-27%20at%209.32.05%E2%80%AFAM.jpg" alt="Screenshot 2024-08-27 at 9.32.05 AM.jpg" />

**Comment by cris-oddball** [comment] 2024-08-27 16:04
Just awaiting feedback from @Jake-Uhteg before closing ticket / deploying to Prod. 

cc/ @EvanParish

**Comment by cris-oddball** [comment] 2024-08-27 17:01
Jake's feedback was that it looks good to him, sending this up through the pipeline to Prod.

**Closed by cris-oddball** 2024-08-27 17:01 UTC
Labels: bug, Notify, QA, QA Reviewed, Dev Reviewed, PM Reviewed
